Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -25,4 +25,15 @@ jobs:
       run: dotnet build --configuration Release --no-restore
 
     - name: Test
-      run: dotnet test --no-restore --verbosity normal --filter FullyQualifiedName=UnitTest.UnitTest1
+      run: |
+        dotnet test --no-restore --verbosity normal --filter FullyQualifiedName=UnitTest.UnitTest1 --logger:"trx;LogFileName=test_results.trx"
+        if [ $? -ne 0 ]; then
+          echo "Tests failed, failing the build"
+          exit 1
+        fi
+
+    - name: Upload Test Results
+      uses: actions/upload-artifact@v2
+      with:
+        name: test-results
+        path: test_results.trx
